<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Management" Version="7.0.0" />
    <PackageReference Include="DirectShowLib" Version="1.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MyApp.Common\MyApp.Common.csproj" />
  </ItemGroup>
</Project>